# Generated by Django 5.1.6 on 2025-03-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('health', 'سلامت'), ('auto', 'خودرو'), ('life', 'زندگی')], max_length=50, verbose_name='نوع بیمه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' مبلغ حق بیمه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.customer', verbose_name='نام و نام خانوادگی مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='تاریخ پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('online', 'آنلاین')], max_length=50, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق')], default='success', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.policy', verbose_name='بیمه')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField(verbose_name='تاریخ ادعا')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه ادعا')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policy', verbose_name='بیمه')),
            ],
        ),
    ]
